version: '3'

services:
  webapp:
    build: .
    command: >
      gunicorn -b 0.0.0.0:50
      --access-logfile -
      --reload
      "webapp.app:app"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/webapp'
    ports:
      - '50:50'